-- Run this entire script in a Snowflake worksheet as ACCOUNTADMIN

USE ROLE ACCOUNTADMIN;

CREATE WAREHOUSE IF NOT EXISTS NDOV_WH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE
    INITIALLY_SUSPENDED = TRUE;

CREATE DATABASE IF NOT EXISTS NDOV_DB;

CREATE SCHEMA IF NOT EXISTS NDOV_DB.RAW;
CREATE SCHEMA IF NOT EXISTS NDOV_DB.STAGING;
CREATE SCHEMA IF NOT EXISTS NDOV_DB.MARTS;

CREATE ROLE IF NOT EXISTS NDOV_ROLE;

GRANT USAGE ON WAREHOUSE NDOV_WH TO ROLE NDOV_ROLE;
GRANT ALL PRIVILEGES ON DATABASE NDOV_DB TO ROLE NDOV_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA NDOV_DB.RAW TO ROLE NDOV_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA NDOV_DB.STAGING TO ROLE NDOV_ROLE;
GRANT ALL PRIVILEGES ON SCHEMA NDOV_DB.MARTS TO ROLE NDOV_ROLE;

GRANT ROLE NDOV_ROLE TO USER YOUR_SNOWFLAKE_USERNAME;